name: Production Build
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [16.x]
        
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Npm Install
      working-directory: ./react-redux-realworld-example-app
      run: |
        npm install
    - name: Production Build
      working-directory: ./react-redux-realworld-example-app
      run: |
        npm run build
    - name: Deploy to S3
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_PRODUCTION_BUCKET_NAME }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        SOURCE_DIR: "./react-redux-realworld-example-app/build"
    - name: Update sentry releases
      working-directory: ./react-redux-realworld-example-app
      run: |   
        # Install the cli
        curl -sL https://sentry.io/get-cli/ | SENTRY_CLI_VERSION="2.2.0" bash
        # Setup configuration values
        export SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }}
        export SENTRY_ORG="radar-productint"
        export SENTRY_PROJECT=react
        export VERSION=`sentry-cli releases propose-version`
        # Workflow to create releases
        sentry-cli releases new "$VERSION"
        sentry-cli releases set-commits "$VERSION" --auto
        sentry-cli releases finalize "$VERSION"
        

